hard_tabs = false
fn_args_layout = "Vertical"
fn_params_layout = "Vertical"
force_multiline_blocks = "true"
indent_style = "Block"
imports_indent = "Block"
imports_layout = "HorizontalVertical"
max_width = 80
reorder_imports = true
