name: Manual Testing

permissions:
  actions: read
  contents: write

on:
  workflow_dispatch

jobs:
  conflictMarkers:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        run: cargo build --release

      - name: Get Cargo Metadata
        id: cargo
        shell: bash
        run: >-
          echo "version=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[-1].version')" >> $GITHUB_OUTPUT &&
          echo "name=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[-1].name')" >> $GITHUB_OUTPUT

      - name: Check if tag is released
        id: tag
        shell: bash
        env:
          TAG: ${{ steps.cargo.outputs.version }}
        run: >-
          git fetch --depth=1 origin "+refs/tags/${TAG}" > /dev/null 2>&1 &&
          echo "exists=true" >> $GITHUB_OUTPUT ||
          echo "exists=false" >> $GITHUB_OUTPUT

      - name: Bundle Release Asset
        id: asset
        shell: bash
        env:
          NAME: ${{ steps.cargo.outputs.name }}
          VERSION: ${{ steps.cargo.outputs.version }}
          OS: ${{ matrix.os }}
        run: >-
          export ARCH="linux" &&
          if [ "$OS" = "macos-latest" ]; then export ARCH="darwin"; fi &&
          if [ "$OS" = "windows-latest" ]; then export ARCH="win32"; fi &&
          export ASSET_NAME="${NAME}-v${VERSION}-${ARCH}-x64.tar.gz" &&
          export ASSET_PATH="${RUNNER_TEMP}/${ASSET_NAME}" &&
          if [ "$OS" = "windows-latest" ]; then export NAME="${NAME}.exe"; fi &&
          export BINARY="./target/release/${NAME}" &&
          if [ "$OS" != "windows-latest" ]; then strip "$BINARY"; fi &&
          if [ "$OS" != "windows-latest" ]; then tar -czf "$ASSET_PATH" -C "./target/release" "$NAME"; fi &&
          if [ "$OS" = "windows-latest" ]; then tar --force-local -czf "$ASSET_PATH" -C "./target/release" "$NAME"; fi &&
          echo "path=$ASSET_PATH" >> $GITHUB_OUTPUT &&
          echo "$ASSET_PATH"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: steps.tag.outputs.exists == 'false'
        with:
          token: ${{ github.token }}
          tag_name: v${{ steps.cargo.outputs.version }}
          files: ${{ steps.asset.outputs.path }}
