name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo test --release
      - name: Get Cargo Metadata
        id: cargo
        run: >-
          echo -n "::set-output name=version::" &&
          cargo metadata --format-version=1 --no-deps |
          jq -r '.packages[0].version' &&
          echo -n "::set-output name=name::" &&
          cargo metadata --format-version=1 --no-deps |
          jq -r '.packages[0].name'
      - name: Check if tag is released
        id: tag
        env:
          TAG: ${{ steps.cargo.outputs.version }}
        run: >-
          git fetch --depth=1 origin "+refs/tags/${TAG}" > /dev/null 2>&1 &&
          echo "::set-output name=exists::true" ||
          echo "::set-output name=exists::false"
      - name: Bundle Release Asset
        id: asset
        env:
          NAME: ${{ steps.cargo.outputs.name }}
          VERSION: ${{ steps.cargo.outputs.version }}
          OS: ${{ matrix.os }}
        run: >-
          export ARCH="linux" &&
          if [ "$OS" = "macos-latest" ]; then export ARCH="darwin"; fi &&
          export ASSET_NAME="${NAME}-v${VERSION}-${ARCH}-x64.tar.gz" &&
          export ASSET_PATH="${RUNNER_TEMP}/${ASSET_NAME}" &&
          export BINARY="./target/release/${NAME}" &&
          strip "$BINARY" &&
          tar -czf "$ASSET_PATH" -C "./target/release" "$NAME" &&
          echo -n "::set-output name=name::" &&
          echo "$ASSET_NAME" &&
          echo -n "::set-output name=path::" &&
          echo "$ASSET_PATH"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: steps.tag.outputs.exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.cargo.outputs.version }}
          files: ${{ steps.asset.outputs.path }}
  retag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create semver tags
        env:
          VERSION: ${{ steps.cargo.outputs.version }}
        run: >-
          git fetch --depth=1 origin "+refs/tags/${TAG}" > /dev/null 2>&1 &&
          export MAJOR_VERSION="$(cut -d'.' -f1 <<< "$VERSION")" &&
          export MINOR_VERSION="$(cut -d'.' -f1-2 <<< "$VERSION")" &&
          git tag "$MAJOR_VERSION" &&
          git tag "$MINOR_VERSION" &&
          git tag "$VERSION"
          git push -f origin "$MAJOR_VERSION" &&
          git push -f origin "$MINOR_VERSION" &&
          git push -f origin "$VERSION"
