name: Test
on:
  - push
jobs:
  test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: kjvalencik/actions/run/wait@0
        with:
          milliseconds: '10000'
